### ISSUE TITLE
Picking up items while holding dye isnt possible

### ISSUE THREAD

**Issue by adrido** [minetest-mods/unifieddyes#4]
If you want to pick up a laying item while holding a dye, it shows a message "This node cant't be colored".

**Comment by VanessaE** [comment]
A similar thing happens if you try to dig something while wielding a dye.  I don't think it's possible to fix this.

**Comment by adrido** [comment]
not tested, but I guess a simple check if pointed_thing.type == "node" ->continue should do it? 
https://github.com/minetest-mods/unifieddyes/blob/master/init.lua#L345

**Comment by VanessaE** [comment]
That doesn't work, unfortunately (I wrote it as `if not pointed_thing or pointed_thing.type ~= "node" return end`) -- it thinks I'm trying to use the dye.  Might be something in the engine getting in the way, or maybe I'm just doing it wrong. :stuck_out_tongue_winking_eye:

**Comment by adrido** [comment]
I found the solution: 
```Lua
if pointed_thing and pointed_thing.type == "object" then
	pointed_thing.ref:punch(player, 0, itemstack:get_tool_capabilities())
	return
end
if not (pointed_thing and pointed_thing.type == "node") then return end  -- if "using" the dye not on a node
```
The solution might be not optimal, because the 2nd argument of punch, the `time_from_last_punch` is 0, because Minetest does not provide a way to get that time. (Or at least I didn't found it :-/ ) 
But the solution works fine for all Items, players and mobs  ( except for mobs_redo because it makes use of that argument)

**Comment by VanessaE** [comment]
Not quite - it almost works, but you don't actually get the dropped object back.

**Comment by adrido** [comment]
Might it be that your inventory was full? Just tested again with latest Minetest game and Minetest engine and all works as it should.

**Comment by VanessaE** [comment]
Wait, you're right, almost - as long as the dropped item is not a portion of dye of the same color as your wield, it works exactly like you wanted, but if the two are the same, the dropped item just disappears.

**Comment by adrido** [comment]
Oh yes you are right. :-( 
And the more odd thing is, that it works again if you wield a stack of 99. 
If you hold 98 then the leftover is added, but 1 is missing.

**Comment by adrido** [comment]
Ha the solution was pretty simple :) 
```lua
if pointed_thing and pointed_thing.type == "object" then
	pointed_thing.ref:punch(player, 0, itemstack:get_tool_capabilities())
	return player:get_wielded_item() -- punch may modified the wielded item, load the new and return it
end
if not (pointed_thing and pointed_thing.type == "node") then return end  -- if "using" the dye not on a node
```

**Comment by VanessaE** [comment]
:tada:  34299b01a065c58c36c0947388b81bb5b8926634

**Comment by VanessaE** [comment]
Works for me!  Thanks!

**Comment by adrido** [comment]
I have to say thanks for this mod and its great support with the new colorization api :-)
